schema = 4
vendorModulesTxt = "# github.com/cyphar/filepath-securejoin v0.3.6\n## explicit; go 1.18\ngithub.com/cyphar/filepath-securejoin\n# github.com/davecgh/go-spew v1.1.1\n## explicit\ngithub.com/davecgh/go-spew/spew\n# github.com/fatih/color v1.18.0\n## explicit; go 1.17\ngithub.com/fatih/color\n# github.com/go-git/gcfg v1.5.1-0.20230307220236-3a3c6141e376\n## explicit; go 1.13\ngithub.com/go-git/gcfg\ngithub.com/go-git/gcfg/scanner\ngithub.com/go-git/gcfg/token\ngithub.com/go-git/gcfg/types\n# github.com/go-git/go-billy/v5 v5.6.1\n## explicit; go 1.21\ngithub.com/go-git/go-billy/v5\ngithub.com/go-git/go-billy/v5/helper/chroot\ngithub.com/go-git/go-billy/v5/helper/polyfill\ngithub.com/go-git/go-billy/v5/memfs\ngithub.com/go-git/go-billy/v5/osfs\ngithub.com/go-git/go-billy/v5/util\n# github.com/go-git/go-git/v5 v5.13.1\n## explicit; go 1.21\ngithub.com/go-git/go-git/v5/internal/path_util\ngithub.com/go-git/go-git/v5/plumbing/format/config\ngithub.com/go-git/go-git/v5/plumbing/format/gitignore\ngithub.com/go-git/go-git/v5/utils/ioutil\n# github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99\n## explicit\ngithub.com/jbenet/go-context/io\n# github.com/mattn/go-colorable v0.1.13\n## explicit; go 1.15\ngithub.com/mattn/go-colorable\n# github.com/mattn/go-isatty v0.0.20\n## explicit; go 1.15\ngithub.com/mattn/go-isatty\n# github.com/pmezard/go-difflib v1.0.0\n## explicit\ngithub.com/pmezard/go-difflib/difflib\n# github.com/spf13/pflag v1.0.5\n## explicit; go 1.12\ngithub.com/spf13/pflag\n# github.com/stretchr/testify v1.10.0\n## explicit; go 1.17\ngithub.com/stretchr/testify/assert\ngithub.com/stretchr/testify/assert/yaml\ngithub.com/stretchr/testify/require\n# golang.org/x/exp v0.0.0-20250103183323-7d7fa50e5329\n## explicit; go 1.22.0\n# golang.org/x/net v0.33.0\n## explicit; go 1.18\ngolang.org/x/net/context\n# golang.org/x/sys v0.28.0\n## explicit; go 1.18\ngolang.org/x/sys/unix\ngolang.org/x/sys/windows\n# gopkg.in/warnings.v0 v0.1.2\n## explicit\ngopkg.in/warnings.v0\n# gopkg.in/yaml.v3 v3.0.1\n## explicit\ngopkg.in/yaml.v3\n"

[mod]
  [mod."github.com/cyphar/filepath-securejoin"]
    version = "v0.3.6"
    hash = "sha256-M1J+wjHnOZ/u2HvR9fry/dpzwGBc23oqEwnD3ym2Z88="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/fatih/color"]
    version = "v1.18.0"
    hash = "sha256-pP5y72FSbi4j/BjyVq/XbAOFjzNjMxZt2R/lFFxGWvY="
  [mod."github.com/go-git/gcfg"]
    version = "v1.5.1-0.20230307220236-3a3c6141e376"
    hash = "sha256-f4k0gSYuo0/q3WOoTxl2eFaj7WZpdz29ih6CKc8Ude8="
  [mod."github.com/go-git/go-billy/v5"]
    version = "v5.6.1"
    hash = "sha256-TvrCU0w/g4oeHNmYpOQJFzAm/E5tYonqN8nAQnw7FTI="
  [mod."github.com/go-git/go-git/v5"]
    version = "v5.13.1"
    hash = "sha256-WWtCQVywLIYGNgBqsSLKKGTDtOdGPjkApRik0Xlrjag="
  [mod."github.com/jbenet/go-context"]
    version = "v0.0.0-20150711004518-d14ea06fba99"
    hash = "sha256-VANNCWNNpARH/ILQV9sCQsBWgyL2iFT+4AHZREpxIWE="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/stretchr/testify"]
    version = "v1.10.0"
    hash = "sha256-fJ4gnPr0vnrOhjQYQwJ3ARDKPsOtA7d4olQmQWR+wpI="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20250103183323-7d7fa50e5329"
    hash = "sha256-LY28ecvACsMYVHp+tfb+YQN+9rAUBfVbTbstgm9JArc="
  [mod."golang.org/x/net"]
    version = "v0.33.0"
    hash = "sha256-9swkU9vp6IflUUqAzK+y8PytSmrKLuryidP3RmRfe0w="
  [mod."golang.org/x/sys"]
    version = "v0.28.0"
    hash = "sha256-kzSlDo5FKsQU9cLefIt2dueGUfz9XuEW+mGSGlPATGc="
  [mod."gopkg.in/warnings.v0"]
    version = "v0.1.2"
    hash = "sha256-ATVL9yEmgYbkJ1DkltDGRn/auGAjqGOfjQyBYyUo8s8="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
