formatters:
  enable:
    - gofmt
    - goimports
    - golines
linters:
  default: all
  disable:
    - depguard
    - funlen
    - gochecknoglobals
    - gosec
    - paralleltest
    - revive
    - wsl
  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable-all: true
version: "2"
