formatters:
  enable:
    - gofmt
    - goimports
    - golines
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - err113
    - exhaustruct
    - forbidigo
    - funlen
    - gocognit
    - gocritic
    - ireturn
    - lll
    - mnd
    - paralleltest
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable-all: true
version: "2"
