#!/usr/bin/env nu

find $env.PROJECT_ROOT ! -path $"($env.PROJECT_ROOT)/.*" -exec snekcheck {} +

nix fmt $env.PROJECT_ROOT -- --quiet

cd $env.SOURCE_ROOT
go mod tidy
go fmt ./...
go vet ./...
golangci-lint run ./...

cd $env.SPEC_ROOT
go mod tidy
go fmt ./...
go vet ./...
golangci-lint run ./...
